name: Deploy to Production

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  # ========== BUILD & DEPLOY ==========
  build-and-deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      #      # ========== BUILD REACT/VITE ==========
      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUDIENCE: ${{ secrets.VITE_AUDIENCE }}
        run: npm run build # Ejecuta 'tsc && vite build'

      # ========== BUILD & PUSH DOCKER ==========
      - name: Set image name
        id: image
        run: |
          echo "name=$(echo 'ghcr.io/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image (PROD)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:dev
          build-args: |
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_AUDIENCE=${{ secrets.VITE_AUDIENCE }}
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}

      # ========== NOTIFY PROVISIONER ==========
      - name: Notify provisioner (PROD)
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/png-provisioner/dispatches \
            -d '{
              "event_type": "service_updated",
              "client_payload": {
                "service": "${{ github.event.repository.name }}",
                "environment": "prod",
                "version": "${{ needs.versioning.outputs.version }}",
                "sha": "${{ github.sha }}"
              }
            }'